import { DatabaseSync } from 'node:sqlite';
import crypto from 'node:crypto';
import bcrypt from 'bcryptjs';
import candidatesRaw from '@/data/candidates.json';

const db = new DatabaseSync(process.env.DATABASE_URL?.replace('file:', '') || 'synapse.db');
db.exec('PRAGMA busy_timeout = 10000; PRAGMA journal_mode = WAL;');
db.exec(`CREATE TABLE IF NOT EXISTS candidates (id TEXT PRIMARY KEY,name TEXT,jobRole TEXT,yearsExperience REAL,education TEXT,status TEXT,email TEXT UNIQUE,passwordHash TEXT,isSeedProfile INTEGER,createdAt TEXT);
CREATE TABLE IF NOT EXISTS missions (id TEXT PRIMARY KEY,candidateId TEXT,day INTEGER,title TEXT,passed INTEGER,skipped INTEGER,attempts INTEGER);
CREATE TABLE IF NOT EXISTS interviews (id TEXT PRIMARY KEY,candidateId TEXT,difficulty TEXT,status TEXT,createdAt TEXT,completedAt TEXT);
CREATE TABLE IF NOT EXISTS turns (id TEXT PRIMARY KEY,interviewId TEXT,role TEXT,content TEXT,day INTEGER,isFollowUp INTEGER,correctness REAL,relevance REAL,gradeNotes TEXT,createdAt TEXT);
CREATE TABLE IF NOT EXISTS reports (id TEXT PRIMARY KEY,interviewId TEXT UNIQUE,overallScore REAL,summary TEXT,strengths TEXT,gaps TEXT,next TEXT,categoryBreakdown TEXT,createdAt TEXT);`);

const id = () => crypto.randomUUID();
const seed = candidatesRaw.candidates as any[];
for (const c of seed) {
    const member = c.member;
    db.prepare('INSERT OR IGNORE INTO candidates VALUES (?,?,?,?,?,?,?,?,?,?)').run(c.id, member.name, member.role, parseFloat(member.yearsExperience), member.education, member.statusBadge, `${c.id}@demo.synapse.local`, bcrypt.hashSync(`demo-${c.id}`, 10), 1, new Date().toISOString());
    if ((db.prepare('SELECT count(*) as n FROM missions WHERE candidateId=?').get(c.id) as any).n === 0) for (const m of c.missions) db.prepare('INSERT INTO missions VALUES (?,?,?,?,?,?,?)').run(id(), c.id, m.day, m.title, m.completed ? 1 : 0, m.skipped ? 1 : 0, m.attempts);
}
export const publicCandidates = () => db.prepare('SELECT id,name,jobRole,yearsExperience,status FROM candidates WHERE isSeedProfile=1 ORDER BY name').all();
export const candidate = (candidateId:string) => db.prepare('SELECT id,name,jobRole,yearsExperience,education,status,isSeedProfile FROM candidates WHERE id=?').get(candidateId) as any;
export const candidateWithMissions = (candidateId:string) => ({...candidate(candidateId), missions: db.prepare('SELECT * FROM missions WHERE candidateId=? ORDER BY day').all(candidateId)});
export function signup(data:any) { const existing=db.prepare('SELECT id FROM candidates WHERE email=?').get(data.email); if(existing) throw new Error('An account with that email already exists.'); const candidateId=id(); db.prepare('INSERT INTO candidates VALUES (?,?,?,?,?,?,?,?,?,?)').run(candidateId,data.name,data.jobRole,Number(data.yearsExperience),data.education,'New candidate',data.email,bcrypt.hashSync(data.password,10),0,new Date().toISOString()); return candidate(candidateId); }
export function authenticate(email:string,password:string) { const c:any=db.prepare('SELECT * FROM candidates WHERE email=?').get(email); return c && bcrypt.compareSync(password,c.passwordHash) ? candidate(c.id) : null; }
export const demo = (candidateId:string) => { const c:any=candidate(candidateId); return c?.isSeedProfile ? c : null; };
const questions=[
 ['Foundations',1,'How do BPE tokenizers affect context-window budgeting for technical content?'],['Structured outputs',2,'How do schema enforcement and validation reduce unreliable model output?'],['RAG systems',8,'Explain why hybrid retrieval with BM25 and dense vectors can improve RAG results.'],['Fine-tuning',10,'How does LoRA reduce the cost of fine-tuning a transformer?'],['Agent systems',17,'Walk through a ReAct loop and one guardrail that prevents infinite loops.']
];
export function startInterview(candidateId:string) { const interviewId=id(); db.prepare('INSERT INTO interviews VALUES (?,?,?,?,?,?)').run(interviewId,candidateId,'intermediate','in_progress',new Date().toISOString(),null); const q=questions[0]; db.prepare('INSERT INTO turns VALUES (?,?,?,?,?,?,?,?,?,?)').run(id(),interviewId,'interviewer',q[2],q[1],0,null,null,null,new Date().toISOString()); return {interviewId,reply:q[2],day:q[1],questionCount:0}; }
function grade(answer:string) { const trimmed=answer.trim(); const weak=/^(h+|idk|ok|no|nah|test|asdf|.)$/i.test(trimmed)||trimmed.split(/\s+/).length<3; if(weak) return {correctness:0.05,relevance:0.05,notes:'This does not substantively address the question.'}; const words=trimmed.split(/\s+/).length; const concepts=/(token|context|schema|valid|retriev|bm25|vector|lora|rank|agent|loop|tool|guardrail|attention)/i.test(trimmed); const correctness=Math.min(.95,(concepts?.55:.25)+Math.min(.35,words/100)); return {correctness,relevance:concepts?.8:.45,notes:concepts?'Relevant concepts were provided; more concrete trade-offs would improve the answer.':'The response is somewhat related but lacks the core technical concepts requested.'}; }
export function submitTurn(interviewId:string,message:string) { const previous:any=db.prepare("SELECT * FROM turns WHERE interviewId=? AND role='interviewer' ORDER BY createdAt DESC LIMIT 1").get(interviewId); const graded=grade(message); db.prepare('INSERT INTO turns VALUES (?,?,?,?,?,?,?,?,?,?)').run(id(),interviewId,'candidate',message,previous?.day||null,0,graded.correctness,graded.relevance,graded.notes,new Date().toISOString()); const count=(db.prepare("SELECT count(*) n FROM turns WHERE interviewId=? AND role='candidate'").get(interviewId) as any).n; if(count>=questions.length) return {done:true, feedback:finish(interviewId)}; const q=questions[count]; const reply=graded.correctness<.3 ? `Let's come back to that with a clearer explanation. ${previous.content}` : q[2]; const day=graded.correctness<.3 ? previous.day : q[1]; db.prepare('INSERT INTO turns VALUES (?,?,?,?,?,?,?,?,?,?)').run(id(),interviewId,'interviewer',reply,day,graded.correctness<.3?1:0,null,null,null,new Date().toISOString()); return {done:false,reply,day,questionCount:count,grade:graded}; }
export function finish(interviewId:string) { const rows:any[]=db.prepare("SELECT * FROM turns WHERE interviewId=? AND role='candidate' AND correctness IS NOT NULL").all(interviewId); const overall=Math.round(100*(rows.reduce((s,r)=>s+r.correctness,0)/Math.max(rows.length,1))); const breakdown=questions.map(([module,day])=>{const a=rows.filter(r=>r.day===day);return {module,score:Math.round(100*(a.reduce((s,r)=>s+r.correctness,0)/Math.max(a.length,1))),daysAsked:[day]};}); const strengths=rows.filter(r=>r.correctness>=.7).map(r=>`Day ${r.day}: ${r.gradeNotes}`); const gaps=rows.filter(r=>r.correctness<.4).map(r=>`Day ${r.day}: ${r.gradeNotes}`); const summary=overall<40?`The ${overall}% score reflects that several answers, including “${rows.find(r=>r.correctness<.4)?.content || 'the submitted response'}”, did not address the question substantively.`:`The ${overall}% score reflects relevant technical answers, with room to add more specific implementation detail.`; const report={overallScore:overall,summary,strengths,gaps,next:gaps.length?['Revisit the lowest-scoring modules and answer with concrete examples.']:['Practice explaining implementation trade-offs aloud.'],categoryBreakdown:breakdown}; db.prepare('INSERT OR REPLACE INTO reports VALUES (?,?,?,?,?,?,?,?,?)').run(id(),interviewId,overall,summary,JSON.stringify(strengths),JSON.stringify(gaps),JSON.stringify(report.next),JSON.stringify(breakdown),new Date().toISOString()); db.prepare("UPDATE interviews SET status='completed',completedAt=? WHERE id=?").run(new Date().toISOString(),interviewId); return report; }
export const interviews=(candidateId:string)=>db.prepare('SELECT i.*,r.overallScore FROM interviews i LEFT JOIN reports r ON r.interviewId=i.id WHERE i.candidateId=? ORDER BY i.createdAt DESC').all(candidateId);
export function report(interviewId:string) { const r:any=db.prepare('SELECT * FROM reports WHERE interviewId=?').get(interviewId); if(!r)return null; return {...r,strengths:JSON.parse(r.strengths),gaps:JSON.parse(r.gaps),next:JSON.parse(r.next),categoryBreakdown:JSON.parse(r.categoryBreakdown),turns:db.prepare('SELECT * FROM turns WHERE interviewId=? ORDER BY createdAt').all(interviewId)}; }
